// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxjazlsquyjjbdqyzrvr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4amF6bHNxdXlqamJkcXl6cnZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNzIyMTcsImV4cCI6MjA2ODk0ODIxN30.VLwq5ap1kQ2rfc610IKhQq5oHfLK8lthfRveJiQxj7g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});